### ISSUE TITLE
Better exception when forgetting to register an event

### ISSUE THREAD

**Issue by janko** [dry-rb/dry-monitor#31]
First of all, thank you for `dry-monitor` and `dry-events` 🙏. I'm really grateful that we have an alternative to `ActiveSupport::Notifications`, and I'm glad to add support for it in Shrine 😃 

I noticed that when I forget to register an event, I don't get a pretty exception:

```rb
require "dry-monitor"

notifications = Dry::Monitor::Notifications.new(:test)
notifications.subscribe("my_event") { |event| }
notifications.instrument("my_event") { }
```
```
Traceback (most recent call last):
        5: from tmp/monitor.rb:5:in `<main>'
        4: from /Users/janko/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/dry-monitor-0.3.1/lib/dry/monitor/notifications.rb:45:in `instrument'
        3: from /Users/janko/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/dry-events-0.1.1/lib/dry/events/publisher.rb:231:in `process'
        2: from /Users/janko/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/dry-events-0.1.1/lib/dry/events/bus.rb:32:in `process'
        1: from /Users/janko/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/dry-events-0.1.1/lib/dry/events/bus.rb:32:in `each'
/Users/janko/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/dry-events-0.1.1/lib/dry/events/bus.rb:33:in `block in process': undefined method `payload' for nil:NilClass (NoMet
hodError)
```

**Comment by mensfeld** [comment]
Hey. I think I fixed that with @davydovanton and @GustavoCaso last week. Could you please try running with `dry-events` master? https://github.com/dry-rb/dry-events

**Comment by janko** [comment]
Confirmed, this is fixed on `master`, thanks!
